Repository karafka/karafka-web, pull requests merged in 2024-03, with the labels that each got.

#282 Auto-qualify topics with DLQ/dlq/dead_letter_queue postfixes to DLQ view
  CHANGELOG.md
  Gemfile.lock
  lib/karafka/web/config.rb
  lib/karafka/web/contracts/config.rb
  lib/karafka/web/ui/pro/controllers/dlq.rb
  lib/karafka/web/version.rb
  spec/lib/karafka/web/contracts/config_spec.rb
  spec/lib/karafka/web/ui/pro/controllers/dlq_spec.rb
Labels: enhancement

#284 Check migration inheritance via ancestors array
  lib/karafka/web/management/migrations/0_base.rb
Labels: migrations

#294 Few small UI improvements
  CHANGELOG.md
  lib/karafka/web/ui/helpers/application_helper.rb
  lib/karafka/web/ui/pro/views/consumers/_breadcrumbs.erb
  lib/karafka/web/ui/pro/views/consumers/_consumer.erb
  lib/karafka/web/ui/pro/views/consumers/index.erb
  lib/karafka/web/ui/pro/views/dashboard/index.erb
  lib/karafka/web/ui/pro/views/health/_partition.erb
  lib/karafka/web/ui/pro/views/jobs/_job.erb
  lib/karafka/web/ui/public/javascripts/charts.js
  lib/karafka/web/ui/public/stylesheets/application.css
  lib/karafka/web/ui/views/consumers/_consumer.erb
  lib/karafka/web/ui/views/jobs/_job.erb
  spec/lib/karafka/web/ui/helpers/application_helper_spec.rb
Labels: enhancement

#296 fix lack of pattern detection
  CHANGELOG.md
  lib/karafka/web/ui/pro/controllers/consumers.rb
  lib/karafka/web/ui/pro/controllers/explorer.rb
  lib/karafka/web/ui/pro/controllers/messages.rb
  lib/karafka/web/ui/pro/controllers/routing.rb
  lib/karafka/web/ui/pro/lib/patterns_detector.rb
  spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb
  spec/lib/karafka/web/ui/pro/controllers/messages_spec.rb
  spec/spec_helper.rb
Labels: bug

#307 support failed headers, etc
  CHANGELOG.md
  lib/karafka/web/ui/lib/safe_runner.rb
  lib/karafka/web/ui/pro/controllers/explorer.rb
  lib/karafka/web/ui/pro/views/explorer/_failed_deserialization.erb
  lib/karafka/web/ui/pro/views/explorer/_message.erb
  lib/karafka/web/ui/pro/views/explorer/message/_metadata.erb
  lib/karafka/web/ui/pro/views/explorer/message/_payload.erb
  lib/karafka/web/ui/pro/views/explorer/message/_payload_actions.erb
  lib/karafka/web/ui/pro/views/explorer/messages/_headers.erb
  lib/karafka/web/ui/pro/views/explorer/messages/_key.erb
  spec/lib/karafka/web/ui/controllers/routing_spec.rb
  spec/lib/karafka/web/ui/lib/safe_runner_spec.rb
  spec/lib/karafka/web/ui/pro/controllers/explorer_spec.rb
  spec/lib/karafka/web/ui/pro/controllers/messages_spec.rb
  spec/support/helpers/topics_manager_helper.rb
Labels: enhancement
