Repository karafka/karafka-web, pull requests merged in 2024-09, with the labels that each got.

#431 deep merge without AS
  CHANGELOG.md
  lib/karafka/web/ui/base.rb
  lib/karafka/web/ui/helpers/application_helper.rb
Labels: bug

#425 Scheduled messages UI support (specs in progress)
  CHANGELOG.md
  Gemfile.lock
  karafka-web.gemspec
  lib/karafka/web/pro/ui/app.rb
  lib/karafka/web/pro/ui/controllers/scheduled_messages/base_controller.rb
  lib/karafka/web/pro/ui/controllers/scheduled_messages/explorer_controller.rb
  lib/karafka/web/pro/ui/controllers/scheduled_messages/schedules_controller.rb
  lib/karafka/web/pro/ui/views/explorer/_partition_option.erb
  lib/karafka/web/pro/ui/views/recurring_tasks/_not_active.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/_breadcrumbs.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/_message.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/_messages.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/partition.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/topic.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/schedules/_breadcrumbs.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/schedules/_no_groups.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/schedules/index.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/schedules/show.erb
  lib/karafka/web/pro/ui/views/search/_breadcrumbs.erb
  lib/karafka/web/pro/ui/views/shared/_navigation.erb
  lib/karafka/web/ui/controllers/base_controller.rb
  lib/karafka/web/ui/helpers/application_helper.rb
  lib/karafka/web/ui/helpers/paths_helper.rb
  lib/karafka/web/ui/models/recurring_tasks/log.rb
  lib/karafka/web/ui/models/recurring_tasks/schedule.rb
  lib/karafka/web/ui/models/recurring_tasks/task.rb
  lib/karafka/web/ui/public/javascripts/application.min.js
  lib/karafka/web/ui/public/javascripts/application.min.js.br
  lib/karafka/web/ui/public/javascripts/application.min.js.gz
  lib/karafka/web/ui/public/javascripts/application.min.js.map
  lib/karafka/web/ui/public/javascripts/components/live_poll.js
  lib/karafka/web/ui/public/stylesheets/application.min.css
  lib/karafka/web/ui/public/stylesheets/application.min.css.br
  lib/karafka/web/ui/public/stylesheets/application.min.css.gz
  lib/karafka/web/ui/public/stylesheets/application.min.css.map
  lib/karafka/web/ui/public/stylesheets/libs/tailwind.css
  lib/karafka/web/ui/views/shared/_breadcrumbs.erb
  lib/karafka/web/ui/views/shared/_navigation.erb
  lib/karafka/web/ui/views/shared/icons/_calendar.erb
  spec/fixtures/scheduled_messages_states/current.msg
  spec/fixtures/scheduled_messages_states/v1.0.0.msg
  spec/lib/karafka/web/pro/ui/controllers/scheduled_messages/explorer_controller_spec.rb
  spec/lib/karafka/web/pro/ui/controllers/scheduled_messages/schedules_controller_spec.rb
  spec/support/fixtures.rb
Labels: scheduled messages

#420 Make navigation menu collapsible on Desktop.
  lib/karafka/web/ui/public/javascripts/application.js
  lib/karafka/web/ui/public/javascripts/application.min.js
  lib/karafka/web/ui/public/javascripts/application.min.js.br
  lib/karafka/web/ui/public/javascripts/application.min.js.gz
  lib/karafka/web/ui/public/javascripts/application.min.js.map
  lib/karafka/web/ui/public/javascripts/components/btn_toggle_manager.js
  lib/karafka/web/ui/public/stylesheets/application.css
  lib/karafka/web/ui/public/stylesheets/application.min.css
  lib/karafka/web/ui/public/stylesheets/application.min.css.br
  lib/karafka/web/ui/public/stylesheets/application.min.css.gz
  lib/karafka/web/ui/public/stylesheets/application.min.css.map
  lib/karafka/web/ui/public/stylesheets/libs/highlight_dark.min.css.gz
  lib/karafka/web/ui/public/stylesheets/libs/highlight_light.min.css.gz
  lib/karafka/web/ui/public/stylesheets/libs/tailwind.css
  lib/karafka/web/ui/views/layout.erb
  lib/karafka/web/ui/views/shared/_brand.erb
  lib/karafka/web/ui/views/shared/_navigation.erb
  lib/karafka/web/ui/views/shared/icons/_chevron.erb
Labels: enhancement

#437 Make navigation menu collapsible on Desktop. (#420)
  lib/karafka/web/pro/ui/views/shared/_navigation.erb
  lib/karafka/web/pro/ui/views/shared/branding/_label.erb
  lib/karafka/web/ui/public/javascripts/application.js
  lib/karafka/web/ui/public/javascripts/application.min.js
  lib/karafka/web/ui/public/javascripts/application.min.js.br
  lib/karafka/web/ui/public/javascripts/application.min.js.gz
  lib/karafka/web/ui/public/javascripts/application.min.js.map
  lib/karafka/web/ui/public/javascripts/components/btn_toggle_manager.js
  lib/karafka/web/ui/public/stylesheets/application.css
  lib/karafka/web/ui/public/stylesheets/application.min.css
  lib/karafka/web/ui/public/stylesheets/application.min.css.br
  lib/karafka/web/ui/public/stylesheets/application.min.css.gz
  lib/karafka/web/ui/public/stylesheets/application.min.css.map
  lib/karafka/web/ui/public/stylesheets/libs/tailwind.css
  lib/karafka/web/ui/views/layout.erb
  lib/karafka/web/ui/views/shared/_brand.erb
  lib/karafka/web/ui/views/shared/_navigation.erb
  lib/karafka/web/ui/views/shared/icons/_chevron.erb
Labels: dashboard

#444 support scheduled messages cancellation
  CHANGELOG.md
  lib/karafka/web/pro/ui/app.rb
  lib/karafka/web/pro/ui/controllers/scheduled_messages/messages_controller.rb
  lib/karafka/web/pro/ui/views/recurring_tasks/_actions.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/_key.erb
  lib/karafka/web/pro/ui/views/scheduled_messages/explorer/_message.erb
  lib/karafka/web/ui/helpers/tailwind_helper.rb
  lib/karafka/web/ui/public/javascripts/application.min.js.gz
  lib/karafka/web/ui/public/stylesheets/application.min.css
  lib/karafka/web/ui/public/stylesheets/application.min.css.br
  lib/karafka/web/ui/public/stylesheets/application.min.css.gz
  lib/karafka/web/ui/public/stylesheets/application.min.css.map
  spec/lib/karafka/web/pro/ui/controllers/recurring_tasks_controller_spec.rb
  spec/lib/karafka/web/pro/ui/controllers/scheduled_messages/messages_controller_spec.rb
  spec/support/helpers/controller_helper.rb
Labels: enhancement

#445 rename probing to tracing
  CHANGELOG.md
  lib/karafka/web/pro/commanding.rb
  lib/karafka/web/pro/commanding/commands/trace.rb
  lib/karafka/web/pro/commanding/listener.rb
  lib/karafka/web/pro/commanding/manager.rb
  lib/karafka/web/pro/ui/app.rb
  lib/karafka/web/pro/ui/controllers/commanding_controller.rb
  lib/karafka/web/pro/ui/views/commands/_command.erb
  lib/karafka/web/pro/ui/views/consumers/_consumer_controls.erb
  lib/karafka/web/pro/ui/views/consumers/consumer/_commands.erb
  spec/fixtures/consumers_commands/v1.0.0_trace.json
  spec/fixtures/consumers_commands/v1.0.0_trace_result.json
  spec/lib/karafka/web/pro/commanding/commands/trace_spec.rb
  spec/lib/karafka/web/pro/commanding/manager_spec.rb
  spec/lib/karafka/web/pro/ui/controllers/commanding_controller_spec.rb
  spec/lib/karafka/web/pro/ui/controllers/commands_controller_spec.rb
  spec/lib/karafka/web/pro/ui/controllers/consumers_controller_spec.rb
Labels: enhancement, commanding
